Pokemon.create(name: "Pikachu")
Pokemon.create(name: "Bulbasaur")
Pokemon.create(name: "Squirtle")
Pokemon.create(name: "Charmander")
Pokemon.create(name: "Eevee")
Pokemon.create(name: "Gyrados")
Pokemon.create(name: "Oddish")
Pokemon.create(name: "Onyx")
Pokemon.create(name: "Geodude")
Pokemon.create(name: "Psyduck")

Trainer.create(name: "Peter")
Trainer.create(name: "Dan")
Trainer.create(name: "Anthony")

Location.create(name: "Flatiron School")
Location.create(name: "Central Park")
Location.create(name: "Statue of Liberty")
Location.create(name: "MoMA")
